networks:
  mc_network_2:
    driver: bridge
services:
  prep_data_instance_2:
    image: busybox:latest
    command:
    - sh
    - -c
    - mkdir -p /data /data/plugins /data/skins && chmod 777 /data /data/plugins /data/skins
      && if [ -d /source_plugins ] && [ -n "$(ls -A /source_plugins 2>/dev/null)"
      ]; then   cp -r /source_plugins/. /data/plugins/; fi; if [ -d /source_skins
      ] && [ -n "$(ls -A /source_skins 2>/dev/null)" ]; then   cp -r /source_skins/.
      /data/skins/; fi; chmod -R 777 /data/plugins /data/skins
    volumes:
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/data/2:/data
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/plugins:/source_plugins:ro
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/skins:/source_skins:ro
    restart: 'no'
  mc_instance_2:
    depends_on:
      prep_data_instance_2:
        condition: service_completed_successfully
    image: itzg/minecraft-server
    tty: true
    network_mode: host
    environment:
      EULA: 'TRUE'
      VERSION: 1.20.4
      TYPE: PAPER
      MODE: survival
      RCON_PORT: 27602
      SERVER_PORT: 27592
      ALLOW_FLIGHT: true
      ONLINE_MODE: false
      SPAWN_PROTECTION: 0
      SEED: '21763048015'
      ENFORCE_SECURE_PROFILE: false
      RCON_PASSWORD: research
      BROADCAST_RCON_TO_OPS: true
      LEVEL_TYPE: minecraft:single_biome_surface
      GENERATOR_SETTINGS: '{"biome":"minecraft:plains", "disable_vegetation": true}'
    volumes:
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/data/2:/data
    healthcheck:
      test:
      - CMD-SHELL
      - mc-monitor status --host localhost --port 27592
      interval: 10s
      timeout: 5s
      retries: 12
  sender_alpha_instance_2:
    image: ojmichel/mc-multiplayer-base:latest
    build:
      context: /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data
      dockerfile: Dockerfile
    depends_on:
      mc_instance_2:
        condition: service_healthy
      receiver_alpha_instance_2:
        condition: service_started
    volumes:
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/output:/output
    environment:
      BOT_NAME: Alpha
      OTHER_BOT_NAME: Bravo
      RECEIVER_HOST: receiver_alpha_instance_2
      RECEIVER_PORT: 8210
      COORD_PORT: 8220
      OTHER_COORD_HOST: sender_bravo_instance_2
      OTHER_COORD_PORT: 8220
      BOT_RNG_SEED: '12347'
      EPISODES_NUM: 8
      EPISODE_START_ID: 0
      EPISODE_TYPES: turnToLook
      MC_HOST: host.docker.internal
      MC_PORT: 27592
      RCON_HOST: host.docker.internal
      RCON_PORT: 27602
      RCON_PASSWORD: research
      BOOTSTRAP_WAIT_TIME: 60
      ENABLE_CAMERA_WAIT: 1
      CAMERA_READY_RETRIES: 300
      CAMERA_READY_CHECK_INTERVAL: 2000
      ITERATIONS_NUM_PER_EPISODE: 1
      MC_VERSION: 1.20.4
      VIEWER_RENDERING_DISABLED: 1
      VIEWER_RECORDING_INTERVAL: 50
      WALK_TIMEOUT: 5
      TELEPORT: 1
      TELEPORT_RADIUS: 250
      WORLD_TYPE: flat
      SMOKE_TEST: 0
      INSTANCE_ID: 2
      OUTPUT_DIR: /output
    extra_hosts:
    - host.docker.internal:host-gateway
    networks:
    - mc_network_2
    command: ./entrypoint_senders.sh
  sender_bravo_instance_2:
    image: ojmichel/mc-multiplayer-base:latest
    build:
      context: /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data
      dockerfile: Dockerfile
    depends_on:
      mc_instance_2:
        condition: service_healthy
      receiver_bravo_instance_2:
        condition: service_started
      sender_alpha_instance_2:
        condition: service_started
    volumes:
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/output:/output
    environment:
      BOT_NAME: Bravo
      OTHER_BOT_NAME: Alpha
      RECEIVER_HOST: receiver_bravo_instance_2
      RECEIVER_PORT: 8210
      COORD_PORT: 8220
      OTHER_COORD_HOST: sender_alpha_instance_2
      OTHER_COORD_PORT: 8220
      BOT_RNG_SEED: '12347'
      EPISODES_NUM: 8
      EPISODE_START_ID: 0
      EPISODE_TYPES: turnToLook
      MC_HOST: host.docker.internal
      MC_PORT: 27592
      RCON_HOST: host.docker.internal
      RCON_PORT: 27602
      RCON_PASSWORD: research
      BOOTSTRAP_WAIT_TIME: 60
      ENABLE_CAMERA_WAIT: 1
      CAMERA_READY_RETRIES: 300
      CAMERA_READY_CHECK_INTERVAL: 2000
      ITERATIONS_NUM_PER_EPISODE: 1
      MC_VERSION: 1.20.4
      VIEWER_RENDERING_DISABLED: 1
      VIEWER_RECORDING_INTERVAL: 50
      WALK_TIMEOUT: 5
      TELEPORT: 1
      TELEPORT_RADIUS: 250
      WORLD_TYPE: flat
      SMOKE_TEST: 0
      INSTANCE_ID: 2
      OUTPUT_DIR: /output
    extra_hosts:
    - host.docker.internal:host-gateway
    networks:
    - mc_network_2
    command: ./entrypoint_senders.sh
  receiver_alpha_instance_2:
    image: ojmichel/mc-multiplayer-base:latest
    environment:
      PORT: 8210
      NAME: Alpha
      INSTANCE_ID: 2
      EPISODE_START_ID: 0
      VIEWER_RENDERING_DISABLED: 1
    tty: true
    volumes:
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/output:/output
    networks:
    - mc_network_2
    command: ./entrypoint_receiver.sh
  receiver_bravo_instance_2:
    image: ojmichel/mc-multiplayer-base:latest
    environment:
      PORT: 8210
      NAME: Bravo
      INSTANCE_ID: 2
      EPISODE_START_ID: 0
      VIEWER_RENDERING_DISABLED: 1
    tty: true
    volumes:
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/output:/output
    networks:
    - mc_network_2
    command: ./entrypoint_receiver.sh
  camera_alpha_instance_2:
    image: ojmichel/mineflayer-spectator-client:latest
    build:
      context: /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/camera
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    depends_on:
      mc_instance_2:
        condition: service_healthy
    environment:
      MC_VERSION: 1.20.4
      MC_HOST: 127.0.0.1
      MC_PORT: 27592
      CAMERA_NAME: CameraAlpha
      DISPLAY: :84
      VNC_PORT: '5205'
      NOVNC_PORT: '6205'
      WIDTH: '1280'
      HEIGHT: '720'
      FPS: '20'
      VNC_PASSWORD: research
      ENABLE_RECORDING: '1'
      RECORDING_PATH: /output/camera_alpha.mp4
    volumes:
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/camera/data_alpha/2:/root
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/camera/output_alpha/2:/output
    extra_hosts:
    - sessionserver.mojang.com:127.0.0.1
    - api.minecraftservices.com:127.0.0.1
    - authserver.mojang.com:127.0.0.1
    - textures.minecraft.net:127.0.0.1
    - pc.realms.minecraft.net:127.0.0.1
  episode_starter_instance_2:
    image: node:20
    network_mode: host
    depends_on:
      mc_instance_2:
        condition: service_healthy
      camera_alpha_instance_2:
        condition: service_started
    working_dir: /app
    environment:
      RCON_HOST: 127.0.0.1
      RCON_PORT: 27602
      RCON_PASSWORD: research
      EPISODE_START_RETRIES: '60'
      EPISODE_REQUIRED_PLAYERS: Alpha,CameraAlpha,Bravo,CameraBravo
      EPISODE_START_COMMAND: episode start Alpha CameraAlpha technoblade.png Bravo
        CameraBravo test.png
    volumes:
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/camera/episode_starter.js:/app/episode_starter.js:ro
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/camera/package.json:/app/package.json:ro
    command:
    - sh
    - -c
    - npm install --omit=dev --no-progress && node episode_starter.js
  camera_bravo_instance_2:
    image: ojmichel/mineflayer-spectator-client:latest
    build:
      context: /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/camera
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    depends_on:
      mc_instance_2:
        condition: service_healthy
    environment:
      MC_VERSION: 1.20.4
      MC_HOST: 127.0.0.1
      MC_PORT: 27592
      CAMERA_NAME: CameraBravo
      DISPLAY: :85
      VNC_PORT: '5206'
      NOVNC_PORT: '6206'
      WIDTH: '1280'
      HEIGHT: '720'
      FPS: '20'
      VNC_PASSWORD: research
      ENABLE_RECORDING: '1'
      RECORDING_PATH: /output/camera_bravo.mp4
    volumes:
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/camera/data_bravo/2:/root
    - /home/tmeehan/snap/snapd-desktop-integration/315/Repos/mc-multiplayer-data/camera/output_bravo/2:/output
    extra_hosts:
    - sessionserver.mojang.com:127.0.0.1
    - api.minecraftservices.com:127.0.0.1
    - authserver.mojang.com:127.0.0.1
    - textures.minecraft.net:127.0.0.1
    - pc.realms.minecraft.net:127.0.0.1
